services:
  - type: web
    name: unique-agency
    runtime: node
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: NEXT_PUBLIC_SITE_URL
        value: https://unique-pvtltd.onrender.com
